// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/group/stats": {
            "get": {
                "description": "Returns a sorted list of all groups and their total data usage.",
                "summary": "List all groups with usage statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field to sort by (total_size_bytes, file_count, name). Default: total_size_bytes",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (ASC, DESC). Default: DESC",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to return. Default: 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip. Default: 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.UserStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/list": {
            "get": {
                "description": "Returns a list of files and directories within the specified path using high-performance hash lookup internally.",
                "summary": "List directory contents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The directory path to list",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include aggregated stats from dir_stats table for directories",
                        "name": "include_stats",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.FileInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/stats": {
            "get": {
                "description": "Returns a sorted list of all users and their total data usage.",
                "summary": "List all users with usage statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Field to sort by (total_size_bytes, file_count, name). Default: total_size_bytes",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (ASC, DESC). Default: DESC",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to return. Default: 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip. Default: 0",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.UserStats"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DirAggregates": {
            "type": "object",
            "properties": {
                "atime_first": {
                    "type": "integer"
                },
                "atime_last": {
                    "type": "integer"
                },
                "ctime_first": {
                    "type": "integer"
                },
                "ctime_last": {
                    "type": "integer"
                },
                "file_count": {
                    "type": "integer"
                },
                "mtime_first": {
                    "type": "integer"
                },
                "mtime_last": {
                    "type": "integer"
                },
                "total_size_bytes": {
                    "type": "integer"
                }
            }
        },
        "main.FileInfo": {
            "type": "object",
            "properties": {
                "aggregates": {
                    "$ref": "#/definitions/main.DirAggregates"
                },
                "atime": {
                    "type": "integer"
                },
                "ctime": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "integer"
                },
                "gid": {
                    "type": "integer"
                },
                "group": {
                    "type": "string"
                },
                "mtime": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "permissions": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "uid": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "main.UserStats": {
            "type": "object",
            "properties": {
                "file_count": {
                    "type": "integer"
                },
                "id_type": {
                    "type": "string"
                },
                "id_value": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "total_size_bytes": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "File System Index API",
	Description:      "API for querying a high-performance filesystem index.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
