// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dir/stats": {
            "get": {
                "description": "Returns detailed metadata for a specific directory. If include_stats=true, returns aggregated info from dir_stats.",
                "summary": "Get directory statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The directory path for stats",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include aggregated stats from dir_stats table",
                        "name": "include_stats",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.FileInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/file/stats": {
            "get": {
                "description": "Returns detailed metadata for a specific file. Returns 400 if the path is a directory.",
                "summary": "Get detailed file statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The path to the file",
                        "name": "path",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.FileInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/list": {
            "get": {
                "description": "Returns a list of files and directories within the specified path using high-performance hash lookup internally.",
                "summary": "List directory contents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The directory path to list",
                        "name": "path",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include aggregated stats from dir_stats table for directories",
                        "name": "include_stats",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.FileInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DirAggregates": {
            "type": "object",
            "properties": {
                "atime_first": {
                    "type": "integer"
                },
                "atime_last": {
                    "type": "integer"
                },
                "ctime_first": {
                    "type": "integer"
                },
                "ctime_last": {
                    "type": "integer"
                },
                "file_count": {
                    "type": "integer"
                },
                "mtime_first": {
                    "type": "integer"
                },
                "mtime_last": {
                    "type": "integer"
                },
                "total_size_bytes": {
                    "type": "integer"
                }
            }
        },
        "main.FileInfo": {
            "type": "object",
            "properties": {
                "aggregates": {
                    "$ref": "#/definitions/main.DirAggregates"
                },
                "atime": {
                    "type": "integer"
                },
                "ctime": {
                    "type": "integer"
                },
                "file_type": {
                    "type": "integer"
                },
                "gid": {
                    "type": "integer"
                },
                "group": {
                    "type": "string"
                },
                "mtime": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "permissions": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "uid": {
                    "type": "integer"
                },
                "user": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "File System Index API",
	Description:      "API for querying a high-performance filesystem index.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
